# ~/.config/starship.toml
add_newline = true
scan_timeout = 10

format = """
[┌>](bold green)$kubernetes$aws
[│](bold green)$python$nodejs
[│](bold green)$git_branch$git_status$git_commit$git_state $directory$package
[└─>](bold green) """

[kubernetes]
format = '[$symbol$context( \($namespace\))](bold yellow)'
disabled = false

[aws]
format = " | [($version$profile)](blue)"


[battery]
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
truncate_to_repo = false
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 5
style = "bold white"
only_detached = false

[git_state]
progress_divider = " of "

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[nodejs]
format="[$symbol($version )](bold blue)"

[python]
symbol = ""
format = "[$symbol $version]($style) | "
style = "bold green"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

[gcloud]
format = 'on [$symbol$account(\($project\))]($style) '
